spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academic_db
    username: root
    password: Copybook04_
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: alextrukhanovich034@gmail.com
    password: tqfp pgvj mgvz ebed
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
